### ISSUE TITLE
Empty lines interfere

### ISSUE THREAD

**Issue by bluemonkmn** [kaiwood/vscode-indentation-level-movement#2]
I am ending up on empty lines when attempting to navigate to the previous line of the same indent level. I think it is happening because there are some blank lines that have the same whitespace indentation level even though these are blank. These should really be ignored.

**Comment by Yzrsah** [comment]
The extension has not been updated in years. You're going to have to fork it yourself

**Comment by kaiwood** [comment]
@Yzrsah Uhm… Not sure how you arrive at the conclusion that this is an unmaintained repository. This is an editor plugin providing a *single* feature and zero external dependencies. As long as no one brings up an issue, there is simple no need for an update just for the sake of updating. 🤔

@bluemonkmn Yep, looks like it stops at lines containing pure whitespace too. Never noticed because I auto trim those lines - but I realise that there are file formats that should not be auto trimmed, so this needs to be fixed. Thanks for the report!

**Comment by kaiwood** [comment]
Fixed via d3a876a93256ce94f7f33acf0a879099914223db
